---
- name: Install DigitalOcean repo key
  apt_key:
    url: https://repos.sonar.digitalocean.com/sonar-agent.asc
    state: present

- name: Install DigitalOcean apt repo
  apt_repository:
    repo: deb https://repos.sonar.digitalocean.com/apt main main
    state: present
    update_cache: yes

- name: Install DigitalOcean agent
  apt:
    name: do-agent
    state: present
